### ISSUE TITLE
Create a P&ID / PDF browser component

### ISSUE THREAD

**Issue by f1cognite** [cognitedata/gearbox.js#134]
Some of the documents we have in CDF is PDFs, SVGs and images and would be good with a component which can visualise them in the browser.

Such component exists in operation support:
<img width="1663" alt="Screenshot 2019-04-24 at 22 33 23" src="https://user-images.githubusercontent.com/31684964/56691756-02abd080-66e1-11e9-9fac-d30743e7d25e.png">

This component need more thought before implementing, but created the issue to keep track of it.

**Comment by andeplane** [comment]
Should we close this one?

**Comment by andeplane** [comment]
Also https://github.com/wojtekmaj/react-pdf

**Comment by polomani** [comment]
opsup has a document renderer for pdf/(images?), we might need to look there

**Comment by fredrik955** [comment]
Don't see the need for it atm
