### ISSUE TITLE
Change ordering of Document categories

### ISSUE THREAD

**Issue by katrinetjolsen** [cognitedata/gearbox.js#157]
**Problem today**
The DocumentTable component sorts document categories seemingly arbitrarily. As a user, it is hard for me quickly to find the documents I'm looking for. E.g., when I investigate pumps, I care about the design data for pumps which lives in one of the pump's Data Sheets.

**Proposed solution**
- Always show "Logic Diagrams" and "P&IDs" on top of the list. These are by far the most used documents. 
- List the other document categories in ascending alphabetical order. 
- In order to explain the ordering, perhaps somehow visually distinguish between Logic Diagrams / P&IDs on top and the rest of the document categories. If not, it might just look like the categories are weirdly out of order again.

**Comment by katrinetjolsen** [comment]
@f1cognite , let me know if you have another mechanism for submitting such feature requests!

**Comment by evancharlton** [comment]
In addition to changing the defaults, allow the end application pass in a sort function so that you don't have to try to support every single individual application.

**Comment by f1cognite** [comment]
@katrinetjolsen We prefer Github-issues like this so it is perfect. I assigned the issue to the tech-lead in Itera (@mrtraser).
Also strongly agree with @evancharlton
