### ISSUE TITLE
Why is TenantSelector super wide?

### ISSUE THREAD

**Issue by evancharlton** [cognitedata/gearbox.js#170]
The TenantSelector component is `width: 100%`, which makes it laughably wide on a computer -- this is even visible in the storybook. It should be `width: auto;` (or whatever will make it be its normal size), perhaps with a `@media (max-width: 400px) { width: 100% }` or something to handle mobile displays.

Additionally, this component is unstyleable -- what's up with that?

**Comment by mrtraser** [comment]
It would be nice to have requirements or common list of styles that should be available for component

**Comment by evancharlton** [comment]
> It would be nice to have requirements or common list of styles that should be available for component

Dunno, sensible ones? I imagine it depends on each component. It's just weird that a UI component library provides UI components which don't accept a `style` prop.

**Comment by mrtraser** [comment]
Got it, will provide additional `style` prop for inline styles.

**Comment by evancharlton** [comment]
antd often provides different `style`-ish props, like `style`, `bodyStyle`, `headerStyle` and so on -- depending on the component's specific purposes.

But the main one here is the width -- it's what's stopping us from adopting it in our app :-)

**Comment by mrtraser** [comment]
Fixed with #187
