### ISSUE TITLE
Console errors in TimeseriesChart component

### ISSUE THREAD

**Issue by follan** [cognitedata/gearbox.js#175]
When using the TimeseriesChart component, this error pops up in the console:
`react-dom.production.min.js:13 Error: <rect> attribute width: A negative value is not valid. ("-50")`

Can be seen here: https://cognitedata.github.io/gearbox.js/?path=/story/timeserieschart--full-description

**Comment by evancharlton** [comment]
FYI, this is an underlying (known) issue in the [griff-react](https://github.com/cognitedata/griff-react) library. It's not actually a problem, but it's just not great.

PRs welcome!

**Comment by follan** [comment]
Created issue and PR in griff-react. Closing this issue
