### ISSUE TITLE
New component: SensorOverlay

### ISSUE THREAD

**Issue by f1cognite** [cognitedata/gearbox.js#2]
Import the component SensorOverlay from https://github.com/cognitedata/operational-intelligence.

![Screenshot 2019-03-12 at 09 09 03](https://user-images.githubusercontent.com/31684964/54184271-877eba00-44a6-11e9-8def-f70790de4052.png)

![Screenshot 2019-03-12 at 09 09 07](https://user-images.githubusercontent.com/31684964/54184257-8188d900-44a6-11e9-9f28-82b5e3b91dbe.png)

**Comment by evancharlton** [comment]
Another fantastic one to create: the landing page that the TenantSelector sits in. Just a big empty styled container with the letter shards in the background, to logo in the corner, and its children  centered horizontally and vertically.

**Comment by Kamillowl** [comment]
@evancharlton so the LandingpageContainer? @evancharlton

**Comment by evancharlton** [comment]
Yes.
