### ISSUE TITLE
AssetSearchAndSelect component (TagSearchAndSelect)

### ISSUE THREAD

**Issue by f1cognite** [cognitedata/gearbox.js#22]
![Screenshot 2019-03-20 at 14 46 09](https://user-images.githubusercontent.com/31684964/54688977-f4392a80-4b1e-11e9-82e4-3f6a183a3d75.png)

Component where you can search for an asset where you limit the search to a root-asset (subtree).

**Comment by mrtraser** [comment]
Duplicate #81 , which is done by @follan
