### ISSUE TITLE
Add any custom OCR services in AssetSearch

### ISSUE THREAD

**Issue by valerii-cognite** [cognitedata/gearbox.js#247]
Referring to this issue https://github.com/cognitedata/operations-support/issues/2138 we want to use internal backend for OCR

**Comment by mrtraser** [comment]
@valerii-cognite, now you can provide URL of your own API via ocrUrl prop of AssetScanner. Also, now I'm adding ability to provide custom transform function to AssetScanner, which will extract founded strings from ocr response.

**Comment by valerii-cognite** [comment]
That's great!
