### ISSUE TITLE
3D model gets bad size and focus problems

### ISSUE THREAD

**Issue by anderscognite** [cognitedata/gearbox.js#258]
I tested this component with the 5.0.8 viewer. The change for 5.0.8 viewer is that it sets some default style `style="width: 640px; height: 480px; min-width: 100%; min-height: 100%; max-width: 100%; max-height: 100%;"` (see https://github.com/cognitedata/3d-viewer/issues/1039).

I now used the latest Model3DViewer component with 5.0.7 (and 5.0.8) in Operational Intelligence, and that gave the following result: 
<img width="2032" alt="Screenshot 2019-05-27 15 49 56" src="https://user-images.githubusercontent.com/34239077/58427009-9ab12700-809e-11e9-87d1-49e2485f91f0.png">

The current implementation has a div that wraps the input text field and the canvas (`.domElement` from the 3D viewer). If I delete that div, everything looks nice, but with that div, I couldn't get a nice size. Let me just add that my knowledge about CSS is very poor. 

Could you help me out here @mrtraser? 

Another thing I noticed is that the hidden text field does not really do what it is supposed to. I had problems with getting the camera control to work even by clicking on the canvas etc.

**Comment by mrtraser** [comment]
@anderscognite, fixed in https://github.com/cognitedata/gearbox.js/pull/259, take a look, please.

**Comment by follan** [comment]
Current fix breaks caching functionality. Reopening issue

**Comment by follan** [comment]
Fixed in #298
