### ISSUE TITLE
MetaEventsProps is not exported

### ISSUE THREAD

**Issue by andeplane** [cognitedata/gearbox.js#275]
I want to use `AssetMeta` to show the list of events only, without header and with custom columns. The docs tells me that I can use `MetaEventsProps`, but it is not available from the gearbox package.

**Comment by anderscognite** [comment]
The issue is not fixed as it is not a TypeScript problem. When using it in a javascript project, I get `Attempted import error: 'MetaEventsProps' is not exported from '@cognite/gearbox'.`.

**Comment by xitman78** [comment]
@anderscognite `MetaEventsProps` is only typescript interface that defines props for inner component showing events. The inner component that presents events is not exported at the moment but typescript type `MetaEventsProps` is definetely exported. I've just checked it.

**Comment by anderscognite** [comment]
Ahh right! Makes sense :) thanks!
