### ISSUE TITLE
[SVGViewer] Current asset will be centered even though it gives invalid view position

### ISSUE THREAD

**Issue by andeplane** [cognitedata/gearbox.js#300]
The _camera_ (or the view) has limitations on where the content can be rendered. However, if `isCurrentAsset` is set, and that object is near the boundary of the SVG, then it will still be rendered approximately in the center. Any small mouse movements will make the content jump to respect the limitations.

I can't show screenshots as this is a public repo, but I can give more info if that is required.

**Comment by anderscognite** [comment]
I think another issue is related to this too. I have the SVGViewer with a certain current asset, but the content is for some reason rendered outside of the SVGViewer area (I have a video that shows this, ask med on Slack for it).

To get the content inside, I can resize the browser window, or click and zoom in the SVG viewer.

**Comment by anderscognite** [comment]
I have a video that shows this if needed!
