### ISSUE TITLE
Add onSearchResult  and dropdownList props for AssetSearch component

### ISSUE THREAD

**Issue by mrtraser** [cognitedata/gearbox.js#309]
- `onSearchResult` callback should trigger when search request finishes with list of assets (applicable for the empty result also)
- `dropdownList` should be a flag that controls dropdown list appearance (don't forget about `onLiveSearchSelect` callback – it should be required) 
- Update storybook examples for AssetSearch

**Comment by mrtraser** [comment]
Related to issue #287

**Comment by khalzmax** [comment]
Merged to master

**Comment by mrtraser** [comment]
Fixed in #329
