### ISSUE TITLE
Why is the document table green by default?

### ISSUE THREAD

**Issue by stonecrafter** [cognitedata/gearbox.js#322]
https://github.com/cognitedata/gearbox.js/blob/35157a1b852b1577821c3ccefd1deb107997f83d/src/components/AssetDocumentsPanel/components/DocumentTable.tsx#L155

None of the examples in storybook shows that way, but when trying to include the component in opint, the whole thing is green, and this line seems to be the culprit. Was it committed by accident?

**Comment by mrtraser** [comment]
Looks it was added accidentally, nice found.

**Comment by joyrostie** [comment]
Yes, line is removed in commit ddda2707de7e0df2198d990ee80839323102a3cb
