### ISSUE TITLE
CSS lint error on $ symbol

### ISSUE THREAD

**Issue by stonecrafter** [cognitedata/gearbox.js#323]
https://github.com/cognitedata/gearbox.js/blob/35157a1b852b1577821c3ccefd1deb107997f83d/src/components/AssetDocumentsPanel/components/DocumentTable.tsx#L168

After cloning the repo, and running yarn, all other lint errors disappear but this one remains:

![Screenshot 2019-06-11 at 13 01 34](https://user-images.githubusercontent.com/3848302/59266950-3c14ad00-8c49-11e9-8304-191eae39ea48.png)

The CSS renders just fine, so either I am missing something (setup instructions -- please update if so 🙂) or some linter configurations in the project is missing?

**Comment by joyrostie** [comment]
@stonecrafter Hey, for live lint we use [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode)and tslint config is next:
`
{
  "extends": [
    "tslint:recommended",
    "tslint-sonarts",
    "tslint-config-prettier",
    "tslint-react"
  ],
  "rules": {
    "ordered-imports": [true],
    "interface-name": [
      true,
      "never-prefix"
    ],
    "object-literal-sort-keys": false,
    "prettier": true,
    "no-console": false,
    "jsx-no-multiline-js": false,
    "array-type": [
      true,
      "array"
    ],
    "jsx-no-lambda": [
      false
    ],
    "no-var-requires": false,
    "no-bitwise": false,
    "member-access": [true, "no-public"]
  },
  "rulesDirectory": [
    "tslint-plugin-prettier"
  ]
}
`

**Comment by joyrostie** [comment]
Double checked from very beginning with cloning and installing dep with yarn - no lint error.

**Comment by mrtraser** [comment]
@stonecrafter, I can't reproduce it either.

**Comment by stonecrafter** [comment]
I got it, was a vscode issue.
