### ISSUE TITLE
Expand description of Gearbox project

### ISSUE THREAD

**Issue by mrtraser** [cognitedata/gearbox.js#369]
Needed to give user clear understanding of what actually library does, what a purpose of it.

@f1cognite suggestion (as an example):
Gearbox is a set of React components natively integrated with Cognite Data Fusion (CDF). Gearbox was built to make it easier to build web applications on top of CDF. We have also created some example applications using gearbox that you can find here (link to javascript-getting-started)

**Comment by joyrostie** [comment]
Do you want to place add this expansion to Github's readme?

**Comment by f1cognite** [comment]
Yes :)
