### ISSUE TITLE
Feature Request: Supporting Multiple Timeseries

### ISSUE THREAD

**Issue by evenstensberg** [cognitedata/gearbox.js#378]
It would be nice to have a chart that contains multiple timeseries connected to a view. This way, one does not need to render distinct charts for a series of connected timeseries. 

For instance (which now throws an error):

```js
import { TimeseriesChartMeta, ThemeProvider } from '@cognite/gearbox';
….
     <ThemeProvider>
             <TimeseriesChartMeta timeseriesId={12345} />
             <TimeseriesChartMeta timeseriesId={6789} />
             <TimeseriesChartMeta timeseriesId={101112} />
     </ThemeProvider>
```

Instead of a single child with TimeSeries (which now is supported)

```js
import { TimeseriesChartMeta, ThemeProvider } from '@cognite/gearbox';
….
     <ThemeProvider>
             <TimeseriesChartMeta timeseriesId={12345} />
     </ThemeProvider>
```

**Comment by polomani** [comment]
@evenstensberg I see that you've closed initial issue on console. Could I see the result of what you've made there? Screenshot or something would be nice

**Comment by polomani** [comment]
I am guessing that initial idea around this has been lost. Closing for now
