### ISSUE TITLE
Research how we can improve the way we write stories

### ISSUE THREAD

**Issue by polomani** [cognitedata/gearbox.js#463]
The storybook is awesome for users, but for gearbox developers it feels quite unpleasant to write a story.
We need to research possible ways of generating story source and properties types documentation.

(Right now we have to manually keep props docs, story source and story text up to date).
We should at least have a way to not write a story source code twice.

Some resources to consider:
https://github.com/storybookjs/storybook/tree/master/addons/storysource
https://github.com/hipstersmoothie/storybook-addon-react-docgen/
https://www.npmjs.com/package/@storybook/addon-info
https://medium.com/storybookjs/writing-a-storybook-addon-to-show-code-examples-97032b00c5d8

**Comment by mrtraser** [comment]
https://github.com/storybookjs/storybook/tree/master/addons/storysource
Cons:
- not convenient to use
- code inside looks to messed to be used in real cases

https://github.com/hipstersmoothie/storybook-addon-react-docgen/
Cons:
- not convenient to use (as a separate tab)
- realy bad in HOC viewing
- do not display props properly

https://github.com/storybookjs/storybook/tree/next/addons/info
Cons:
- does not show prop types properly
- realy bad markup for code

https://www.docz.site/
Pros:
- markup and code examples in single file
- playground available right out of the box
- nice markup

Cons:
- we need redo all stories
- change build and deploying pipelines
- typescript props poorly supported

What do you think guys – @polomani, @fredrik955 ?

**Comment by nalaka** [comment]
@polomani - have you looked at the [DocsPage](https://medium.com/storybookjs/storybook-docspage-e185bc3622bf) feature introduced in Storybook 5.2? We can write markdown and use MDX.

**Comment by Meemaw** [comment]
This might be interesting for you: https://medium.com/storybookjs/component-story-format-66f4c32366df

We migrated to CSF in https://github.com/cognitedata/operational-intelligence/pull/3768 and it is awesome (we use Storybooks as source of truth for tests as well)

**Comment by mrtraser** [comment]
Decided to use addon-docs of storybook to write stories in MDX format
