### ISSUE TITLE
Add base-url option to TenantSelector

### ISSUE THREAD

**Issue by f1cognite** [cognitedata/gearbox.js#47]
Our TenantSelector only allows you to select a tenant (project name) from the `https://api.cognitedata.com` api. But we also have other base urls like `https://*.cognitedata.com` where other tenants live. So maybe add a new prop to TenantSelector where you can enable a baseUrl field to override the base url.

**Comment by evancharlton** [comment]
Strictly speaking, the TenantSelector doesn't need to know about the base URL because it doesn't actually talk to the API at all. I guess what we need is a way to have an "advanced options" panel that we can optionally add in there, so we can render whatever options we (the app) want.
