### ISSUE TITLE
Timeseries ruler doesn't display multiple labels (they overlap)

### ISSUE THREAD

**Issue by polomani** [cognitedata/gearbox.js#476]
Using ruler with multiple timeseries in TimeSeriesChart doesn't work.
Labels are rendered on top of each other and user can only see the top one.

<img width="978" alt="Screenshot 2019-10-31 at 13 21 44" src="https://user-images.githubusercontent.com/10908415/68017302-b4cae300-fc96-11e9-88b3-6cd8bb4b46e9.png">

![image](https://user-images.githubusercontent.com/10908415/68017435-007d8c80-fc97-11e9-8d58-f9a4dc99b1f0.png)

We should disable griff-react ruler label

**Comment by nalaka** [comment]
Fixed by PR #501
