### ISSUE TITLE
New cookie-policy in Chrome.

### ISSUE THREAD

**Issue by henning-kvinnesland** [cognitedata/gearbox.js#482]
![image](https://user-images.githubusercontent.com/39047273/68108038-ee922880-fee6-11e9-8f31-eaf928b57e97.png). For now a warning is generated, but it might become problematic in the future.

**Comment by polomani** [comment]
when do you get this warning? it doesn't seem that we are using cookies in gearbox

**Comment by annitya** [comment]
It disappeared without rhyme or reason. Feel free to close the issue.
