### ISSUE TITLE
Research how OpInt syncs timeseries preview with TimeseriesChart (last datapoint)

### ISSUE THREAD

**Issue by polomani** [cognitedata/gearbox.js#485]

**Comment by mrtraser** [comment]
so, logic of TimeseriesPreview component in OpInt:
- by default, TimeseriesPreview fetches the latest point for timeseries with a provided interval and renders result of this call. It does not have any sync with TimeseriesChart at all. Moreover, auto-refresh button has no effect on TimeseriesChart, chart renders latest datapoints only if you drag timeframe or act on the chart in another way (zoom-in for example).
- TimeseriesPreview shows different value than the latest fetched datapoint in case of moving mouse pointer above chart and displaying datapoints value at the highlighted timestamp.

So, TimeseriesPreview in OpInt has input prop with value to display and if this value is undefined, it fetches the latest datapoint to display without syncing this value with TimeseriesChart

**Comment by polomani** [comment]
solved
