### ISSUE TITLE
Time Period selection bar for TimeseriesChart

### ISSUE THREAD

**Issue by hasanka-madhushan** [cognitedata/gearbox.js#504]
It would be very useful to have a **time period selection bar** like in OpInt for the `TimeseriesChart` component - please refer screenshot.

![time-periods-in-opint](https://user-images.githubusercontent.com/56960307/69326543-fb967200-0c71-11ea-94f8-54d03e4d407e.png)

**Comment by polomani** [comment]
@hasanka-madhushan can you use timeseries meta for that?
https://pr-501.gearboxjs.preview.cogniteapp.com/?path=/story/timeserieschartmeta--full-description

**Comment by hasankamadhushan-dev** [comment]
thank you for getting back, It was possible to use timeseries meta and It fulfils our requirement.You can close this issue.
