### ISSUE TITLE
Move to eslint from tslint

### ISSUE THREAD

**Issue by polomani** [cognitedata/gearbox.js#511]
Tslint is going to be deprecated soon, we need to move to eslint instead, which will give more flexibility in the future. (like support mdx files)

**Comment by mrtraser** [comment]
Reason:
https://medium.com/palantir/tslint-in-2019-1a144c2317a9

Roadmap for TSLint:
https://github.com/palantir/tslint/issues/4534

We should move to use this plugin:
https://github.com/typescript-eslint/typescript-eslint

**Comment by polomani** [comment]
done, many thanks to @Tapped
