### ISSUE TITLE
Missing delimiters in csv-export.

### ISSUE THREAD

**Issue by annitya** [cognitedata/gearbox.js#515]
1. Check `Format timestamp?`
2. Select `;` as delimiter.

![image](https://user-images.githubusercontent.com/727305/69650730-53b4e600-106f-11ea-8500-12e02498c8cb.png)

3. Highlighted text is missing a delimiter.
![image](https://user-images.githubusercontent.com/727305/69651060-caea7a00-106f-11ea-81ab-3ab0a1f37ab9.png)

**Comment by mrtraser** [comment]
Closed via #528
