### ISSUE TITLE
Tooltips for hidden series remains visible.

### ISSUE THREAD

**Issue by annitya** [cognitedata/gearbox.js#516]
![image](https://user-images.githubusercontent.com/727305/69651600-9fb45a80-1070-11ea-9671-ed9374a1105b.png)

Series with gray indicators on the right hand side are hidden, but the various tooltips remains visible.

**Comment by polomani** [comment]
could be fixed in https://github.com/cognitedata/gearbox.js/pull/501

**Comment by polomani** [comment]
fixed in #535
