### ISSUE TITLE
Improvements in the new .mdx storybook 

### ISSUE THREAD

**Issue by polomani** [cognitedata/gearbox.js#553]
We should go though all stories in a new `docs/configure-addon-docs`  and improve it in places where there is something that doesn't look good.

Some places:
- model 3d viewer : screenshot example should use reactive way of adding pictures, also it shouldn't stretch the page that much. maybe show just the last picture?
- make sure all components have working `<props/>` and explanation is explanatory
 - all of components have stories in one mdx file (not split between basic/examples anymore)
- have something better then handlers like `onClick => e => console.log(e)` as it doesn't even show up in the storybook (developer needs to open dev-console to see the result). previously we used `action(...)`  addon but I am guessing  it doen't work with addon-docs. Please, come up with something here. Maybe just render something ourself?
- have better fake timeseries data in our chart stories (expecially https://cognitedata.github.io/gearbox.js/?path=/story/timeserieschart-examples--multiple) at least we can have two timeseries that almost overlaps (both of them uses sin/cos function without any shifting even)

**Comment by nalaka** [comment]
@polomani @mrtraser - current status of this issue:

Except for the below, others and a few that is not mentioned here was fixed and merged to master and released.

(1) Approach to console logging

Until Storybook project releases a proper solution to this we decided to stick with `console.log()` - pls refer #568

(2) Have better fake timeseries data in our chart stories

PR #606 for this under review
