### ISSUE TITLE
Allow for custom text in TimeseriesPreview component

### ISSUE THREAD

**Issue by hernil** [cognitedata/gearbox.js#554]
From #481 

> User should be able what name should be displayed (metadata or name, id etc).

For now only the value field can be customized. We would like that to extend to the fields that for now display name and description of the timeseries. 

A use case for this will for us be to show the name of a TimeSeries' parent Asset instead of the name of the ts itself, so maybe keep that in mind 😄

**Comment by mrtraser** [comment]
Closed by #614
