### ISSUE TITLE
[mdx-stories] Add story for TimeseriesChart ruler prop

### ISSUE THREAD

**Issue by mrtraser** [cognitedata/gearbox.js#582]

**Comment by rumeshwick** [comment]
@mrtraser I can see "Ruler" prop story is already added in the "configure-addon-docs" branch. But when compared to old format, the description is missing in new format. So under this task i will update the missing description.

![Screen Shot 2020-01-13 at 11 40 17 AM](https://user-images.githubusercontent.com/4345813/72236021-28745f00-35fb-11ea-9cf6-0c1895270421.png)

**Comment by mrtraser** [comment]
@nalaka changed this component and already created a proper story for it. You need to check the release branch to take @nalaka's story as an example

**Comment by mrtraser** [comment]
Closed by #614
