### ISSUE TITLE
[TimeseriesChart]: track Y-axis alignment research

### ISSUE THREAD

**Issue by mrtraser** [cognitedata/gearbox.js#612]
Reseach feasibility to provide a callback for Y-axis manual realignment (by zooming/panning Y-axis) to track Y-axes subdomain changes.

**Comment by amevck** [comment]
According to my research on this, I have found that griff-react have exposed a property called `onUpdateDomains` which gives an object of type 
```typescript
{ 
 xxx:
  { 
   time : [ number, number ],
   x : [ number, number ],
   y : [ number, number ],
  } 
}
```
as a callback parameter on the given call back function when changing `y-domain` or `x-domain`.
```
xxx - time series Id
time - time domain [min,max] values 
x - x domain [min,max] values 
y - y domain [min,max] values 
```
Now we can do either

- Expose this call-back `onUpdateDomains` from TimeseriesChart (take less effort)

   or 

- Handle this inside Time Series chart and expose `onUpdateYDomain` call-back

**Comment by mrtraser** [comment]
I would continue with the second option – handle `onUpdateDomains` callback from `griff-react` inside `TimeseriesChart` component and provide `onUpdateYDomain` prop

**Comment by nalaka** [comment]
Closing this as #601 is ready.

**Comment by man-csl** [comment]
> I would continue with the second option – handle `onUpdateDomains` callback from `griff-react` inside `TimeseriesChart` component and provide `onUpdateYDomain` prop

Current callback from griff-react does not specify which domain got changed - whether it was ydomain, xdomain. It only gives latest values after the change. @amevck please correct me if I am wrong. Therefore filtering out ydomain changes requires us to keep current yDomain and compare it with the latest ydomain we get from the griff callback. This looks bad and also can lead to issues if griff-react suppresses callbacks when domain change was requested through its API's programmatically. Unless there is a clear need from users of Gearbox to expose yDomainChange call back at the moment, my suggestion is to request this feature from griff-react it-self and expose once it is implemented.
